import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../../public/fontawesome-free/css/all.min.css";
import "../../public/bootstrap/css/bootstrap.min.css";
import "../../public/bootstrap/css/dataTables.bootstrap4.min.css";
import "../../public/css/sb-admin-2.min.css";
import Providers from "../lib/auth/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
